DROP TABLE IF EXISTS `X_preview`;
CREATE TABLE `X_preview` (
`id` INT(11) NOT NULL AUTO_INCREMENT,
`file_name` VARCHAR(255) DEFAULT  NULL COMMENT '名',
`content` LONGTEXT DEFAULT  NULL COMMENT '名',
`gmt_create` DATETIME COMMENT '创建时间',
`gmt_modified` DATETIME COMMENT '更新时间',
PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
